import requests
import json

url = requests.get("https://github.com/SkolotajsZelukins/macibu_api/blob/main/saraksts.json") 
info = requests.get(url).json()
print(info)
print(info['result']['records'])
# response = requests.get("https://github.com/SkolotajsZelukins/macibu_api/blob/main/saraksts.json") 
# print(response.status_code)
# print(response.text)
# print(response.json())
# print(response.headers)
# print(response.url)
# print(response.encoding)
# print(response.content)
# print(response.raw)
# print(response.raise_for_status())
# print(response.request)
# print(response.connection)
# print(response.cookies)
# print(response.elapsed)
# print(response.links)
print(response.ok)
# print(response.reason)
print(response.text)

