import requests
import json
response = requests.get('https://github.com/AleksandrZelukin/12klase_flask_vietne/blob/main/templates/about.html')
# print(response.status_code)
print(response.text)
# print(response.json())
# print(response.headers)
# print(response.url)
# print(response.encoding)
# print(response.content)
# print(response.raw)
# print(response.raise_for_status())
# print(response.request)
# print(response.connection)
# print(response.cookies)
# print(response.elapsed)
# print(response.links)
# print(response.ok)
# print(response.reason)
# print(response.text)

